name: Check Update

on:
  push:
  workflow_dispatch:

env:
  APP_ID: 1829350

jobs:
  check:
    name: Check Update
    runs-on: ubuntu-latest
    steps:
      - name: Get App Info
        run: |
          curl -X GET "https://api.steamcmd.net/v1/info/${{ env.APP_ID }}" -o data.json
          cat data.json
      - name: Parse Data
        id: parsed_data
        run: |
          echo '::set-output name=public::'$(jq -r --arg APP_ID "${{ env.APP_ID }}" '.data.[$APP_ID].depots.branches.public' data.json)
          cat data.json
      - name: Fetch Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: data.json
          key: ${{ hashFiles('data.json') }}
      - name: Compare Data
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "test"
