name: Check Update

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


env:
  APP_ID: 1829350

jobs:
  check:
    name: Check Update
    runs-on: ubuntu-latest
    steps:
      - name: Get App Info
        run: |
          curl -X GET "https://api.steamcmd.net/v1/info/${{ env.APP_ID }}" -o data.json
      - name: Get Public Build
        run: |
          echo $(jq -r --arg APP_ID "${{ env.APP_ID }}" '.data[$APP_ID].depots.branches.public' data.json) > data.json
      - name: Fetch Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: data.json
          key: ${{ hashFiles('data.json') }}
      - name: Trigger New Build
        uses: peter-evans/repository-dispatch@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: new-version
